### ISSUE TITLE
1.0.0-beta Release Checklist

### ISSUE THREAD

**Issue by silverbackdan** [silverbackis/bwstarter_nuxt_modules#1]
- [ ] Fix image loading size issue on article collection
- [ ] Admin bar gets stuck on 'saving' if auto-save used and then turned off
- [ ] The login form should be destroyed as the page is left. Other forms should be destroyed when the page is left and the form was submitted successfully.
- [ ] Child pages which are a component group should be detected and rendered (bug fix)
- [ ] Admin should be able to upload files (Dropzone.js will be used) This will apply to all images using the ImageLoader component
- [ ] Gallery items administration
- [ ] Dynamic pages add/delete functionality
- [ ] Gallery item links should include `rel=preload`
- [ ] Colour contrast adjusted to improve lighthouse score for accessibility
